### ISSUE TITLE
Error with command "Subscription"

### ISSUE THREAD

**Issue by MorpheusSohn** [eknoes/covid-bot#85]
I have noticed that if you send "abo NRW" to the bot, it subscribes to the independent city of Dortmund. Should this be the case?!

[Bild_2021-02-10_115508](https://user-images.githubusercontent.com/47597136/107500745-d2c00c80-6b96-11eb-8a26-72c9b2f7dee3.png)

**Comment by eknoes** [comment]
No it should not. Thanks for the hint!

Currently it does not find it directly in the RKI data and searches Open Street Map which returns Dortmund then. We should either introduce abbrevations or should - for an online search - show up "parents", so a user would at least get "Choose from Dortmund or Nordrhein Westfalen".

**Comment by eknoes** [comment]
Habe ich behoben, das ist in den nächsten Minuten live. Danke!

**Comment by MorpheusSohn** [comment]
The introduction of abbreviations seems to me to make sense - car registration plates could possibly be well suited for this, couldn't they? 

A subscription for the incidence of one or more federal states is not yet implemented, is it?

**Comment by eknoes** [comment]
I think it would make sense, but it had to be maintained by hand I guess.

Currently the mechanism when searching is as follows:
1. Query local database for matches
2. On exact match, return this
3. On several matches, return the List of matches

If there is no result, an online search using Open Street Map (OSM) is made. This returns a distinct list of Districts where we have data for and now -- this is new due to your but report -- also their parents. E.g. in your case, searching OSM returned Dortmund, now we add also NRW as it is the *parent* of Dortmund.

If this process returns more than 15 districts, we tell the user to be more specific.



We could maintain a seperate database with abbreviations and use e.g. [this data](https://www.govdata.de/suchen/-/details/kfz-kennzeichen-deutschland3785e) but imho we already have enough "layers" to find the district someone searches for and I would rather focus on implementing e.g. #87 or such. I opened a new Issue #88 for this topic :)

**Comment by eknoes** [comment]
> A subscription for the incidence of one or more federal states is not yet implemented, is it?

It is implemented, you can subscribe to as many federal states as you want to. Does it not work?
